
epayco.publicKey = e43fdbb8e33df236d78de5aa0984a8b2
epayco.privateKey = d7096a7c13827c4b8bcdc83e628e3f62
epayco.miepaycoUrl = https://sandbox.epayco.co
epayco.responseUrl = http://127.0.0.1:8080/epayco-response?idPago={idPago}
epayco.confirmationUrl = http://127.0.0.1:8080/epayco-confirmation?idPago={idPago}

# Pega aquí el client secret del OAuth Web de Google.
google.clientSecret = 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